### ISSUE TITLE
Retain Flag update

### ISSUE THREAD

**Issue by stevencroft** [BobWatson/wmp2mqtt-docker#1]
Hi Bob,
I added some new functionality to optionally set a retain flag on the messages sent to MQTT so that in the event of a restart MQTT will persist the last state of the HVAC status.

Are you able to update this docker image and ideally map the --retain parameter?

cheers
Steve

**Comment by BobWatson** [comment]
Yep - now that it's merged, will sort out in the next day. Thanks for the update!

**Comment by stevencroft** [comment]
Thanks!

**Comment by BobWatson** [comment]
Haven't forgotten - just caught up with other things. Hope to sort out this weekend.

**Comment by stevencroft** [comment]
No worries at all. Thanks again for creating the dockerised version its awesome!
________________________________

**Comment by stevencroft** [comment]
Hi Bob, just giving this one a nudge.
Can I do anything to help?

**Comment by BobWatson** [comment]
Sorry - should have given me a nudge a few weeks ago. Have updated (and pushed new image to Docker Hub).

**Comment by stevencroft** [comment]
Fantastic! thanks!
________________________________
